# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: moab/v0/api.proto for package 'Evrblk.Moab.V0'

require 'grpc'
require 'evrblk/moab/v0/api_pb'

module Evrblk
  module Moab
    module V0
      module MoabApi
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'com.evrblk.moab.v0.MoabApi'

          rpc :CreateQueue, ::Evrblk::Moab::V0::CreateQueueRequest, ::Evrblk::Moab::V0::CreateQueueResponse
          rpc :GetQueue, ::Evrblk::Moab::V0::GetQueueRequest, ::Evrblk::Moab::V0::GetQueueResponse
          rpc :UpdateQueue, ::Evrblk::Moab::V0::UpdateQueueRequest, ::Evrblk::Moab::V0::UpdateQueueResponse
          rpc :DeleteQueue, ::Evrblk::Moab::V0::DeleteQueueRequest, ::Evrblk::Moab::V0::DeleteQueueResponse
          rpc :ListQueues, ::Evrblk::Moab::V0::ListQueuesRequest, ::Evrblk::Moab::V0::ListQueuesResponse
          rpc :GetTask, ::Evrblk::Moab::V0::GetTaskRequest, ::Evrblk::Moab::V0::GetTaskResponse
          rpc :ListTasks, ::Evrblk::Moab::V0::ListTasksRequest, ::Evrblk::Moab::V0::ListTasksResponse
          rpc :Enqueue, ::Evrblk::Moab::V0::EnqueueRequest, ::Evrblk::Moab::V0::EnqueueResponse
          rpc :Dequeue, ::Evrblk::Moab::V0::DequeueRequest, ::Evrblk::Moab::V0::DequeueResponse
          rpc :ReportStatus, ::Evrblk::Moab::V0::ReportStatusRequest, ::Evrblk::Moab::V0::ReportStatusResponse
          rpc :DeleteTasks, ::Evrblk::Moab::V0::DeleteTasksRequest, ::Evrblk::Moab::V0::DeleteTasksResponse
          rpc :RestartTasks, ::Evrblk::Moab::V0::RestartTasksRequest, ::Evrblk::Moab::V0::RestartTasksResponse
          rpc :PurgeQueue, ::Evrblk::Moab::V0::PurgeQueueRequest, ::Evrblk::Moab::V0::PurgeQueueResponse
          rpc :CreateSchedule, ::Evrblk::Moab::V0::CreateScheduleRequest, ::Evrblk::Moab::V0::CreateScheduleResponse
          rpc :GetSchedule, ::Evrblk::Moab::V0::GetScheduleRequest, ::Evrblk::Moab::V0::GetScheduleResponse
          rpc :UpdateSchedule, ::Evrblk::Moab::V0::UpdateScheduleRequest, ::Evrblk::Moab::V0::UpdateScheduleResponse
          rpc :DeleteSchedule, ::Evrblk::Moab::V0::DeleteScheduleRequest, ::Evrblk::Moab::V0::DeleteScheduleResponse
          rpc :ListSchedules, ::Evrblk::Moab::V0::ListSchedulesRequest, ::Evrblk::Moab::V0::ListSchedulesResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
