# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: moab/preview/api.proto for package 'Evrblk.Moab.Preview'

require 'grpc'
require 'evrblk/moab/preview/api_pb'

module Evrblk
  module Moab
    module Preview
      module MoabPreviewApi
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'com.evrblk.moab.preview.MoabPreviewApi'

          rpc :CreateQueue, ::Evrblk::Moab::Preview::CreateQueueRequest, ::Evrblk::Moab::Preview::CreateQueueResponse
          rpc :GetQueue, ::Evrblk::Moab::Preview::GetQueueRequest, ::Evrblk::Moab::Preview::GetQueueResponse
          rpc :UpdateQueue, ::Evrblk::Moab::Preview::UpdateQueueRequest, ::Evrblk::Moab::Preview::UpdateQueueResponse
          rpc :DeleteQueue, ::Evrblk::Moab::Preview::DeleteQueueRequest, ::Evrblk::Moab::Preview::DeleteQueueResponse
          rpc :ListQueues, ::Evrblk::Moab::Preview::ListQueuesRequest, ::Evrblk::Moab::Preview::ListQueuesResponse
          rpc :GetTask, ::Evrblk::Moab::Preview::GetTaskRequest, ::Evrblk::Moab::Preview::GetTaskResponse
          rpc :Enqueue, ::Evrblk::Moab::Preview::EnqueueRequest, ::Evrblk::Moab::Preview::EnqueueResponse
          rpc :Dequeue, ::Evrblk::Moab::Preview::DequeueRequest, ::Evrblk::Moab::Preview::DequeueResponse
          rpc :ReportStatus, ::Evrblk::Moab::Preview::ReportStatusRequest, ::Evrblk::Moab::Preview::ReportStatusResponse
          rpc :DeleteTasks, ::Evrblk::Moab::Preview::DeleteTasksRequest, ::Evrblk::Moab::Preview::DeleteTasksResponse
          rpc :RestartTasks, ::Evrblk::Moab::Preview::RestartTasksRequest, ::Evrblk::Moab::Preview::RestartTasksResponse
          rpc :PurgeQueue, ::Evrblk::Moab::Preview::PurgeQueueRequest, ::Evrblk::Moab::Preview::PurgeQueueResponse
          rpc :CreateSchedule, ::Evrblk::Moab::Preview::CreateScheduleRequest, ::Evrblk::Moab::Preview::CreateScheduleResponse
          rpc :GetSchedule, ::Evrblk::Moab::Preview::GetScheduleRequest, ::Evrblk::Moab::Preview::GetScheduleResponse
          rpc :UpdateSchedule, ::Evrblk::Moab::Preview::UpdateScheduleRequest, ::Evrblk::Moab::Preview::UpdateScheduleResponse
          rpc :DeleteSchedule, ::Evrblk::Moab::Preview::DeleteScheduleRequest, ::Evrblk::Moab::Preview::DeleteScheduleResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
