# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: grackle/preview/api.proto for package 'Evrblk.Grackle.Preview'

require 'grpc'
require 'evrblk/grackle/preview/api_pb'

module Evrblk
  module Grackle
    module Preview
      module GracklePreviewApi
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'com.evrblk.grackle.preview.GracklePreviewApi'

          rpc :CreateNamespace, ::Evrblk::Grackle::Preview::CreateNamespaceRequest, ::Evrblk::Grackle::Preview::CreateNamespaceResponse
          rpc :ListNamespaces, ::Evrblk::Grackle::Preview::ListNamespacesRequest, ::Evrblk::Grackle::Preview::ListNamespacesResponse
          rpc :GetNamespace, ::Evrblk::Grackle::Preview::GetNamespaceRequest, ::Evrblk::Grackle::Preview::GetNamespaceResponse
          rpc :DeleteNamespace, ::Evrblk::Grackle::Preview::DeleteNamespaceRequest, ::Evrblk::Grackle::Preview::DeleteNamespaceResponse
          rpc :UpdateNamespace, ::Evrblk::Grackle::Preview::UpdateNamespaceRequest, ::Evrblk::Grackle::Preview::UpdateNamespaceResponse
          rpc :CreateSemaphore, ::Evrblk::Grackle::Preview::CreateSemaphoreRequest, ::Evrblk::Grackle::Preview::CreateSemaphoreResponse
          rpc :ListSemaphores, ::Evrblk::Grackle::Preview::ListSemaphoresRequest, ::Evrblk::Grackle::Preview::ListSemaphoresResponse
          rpc :GetSemaphore, ::Evrblk::Grackle::Preview::GetSemaphoreRequest, ::Evrblk::Grackle::Preview::GetSemaphoreResponse
          rpc :AcquireSemaphore, ::Evrblk::Grackle::Preview::AcquireSemaphoreRequest, ::Evrblk::Grackle::Preview::AcquireSemaphoreResponse
          rpc :ReleaseSemaphore, ::Evrblk::Grackle::Preview::ReleaseSemaphoreRequest, ::Evrblk::Grackle::Preview::ReleaseSemaphoreResponse
          rpc :UpdateSemaphore, ::Evrblk::Grackle::Preview::UpdateSemaphoreRequest, ::Evrblk::Grackle::Preview::UpdateSemaphoreResponse
          rpc :DeleteSemaphore, ::Evrblk::Grackle::Preview::DeleteSemaphoreRequest, ::Evrblk::Grackle::Preview::DeleteSemaphoreResponse
          rpc :CreateWaitGroup, ::Evrblk::Grackle::Preview::CreateWaitGroupRequest, ::Evrblk::Grackle::Preview::CreateWaitGroupResponse
          rpc :ListWaitGroups, ::Evrblk::Grackle::Preview::ListWaitGroupsRequest, ::Evrblk::Grackle::Preview::ListWaitGroupsResponse
          rpc :GetWaitGroup, ::Evrblk::Grackle::Preview::GetWaitGroupRequest, ::Evrblk::Grackle::Preview::GetWaitGroupResponse
          rpc :DeleteWaitGroup, ::Evrblk::Grackle::Preview::DeleteWaitGroupRequest, ::Evrblk::Grackle::Preview::DeleteWaitGroupResponse
          rpc :AddJobsToWaitGroup, ::Evrblk::Grackle::Preview::AddJobsToWaitGroupRequest, ::Evrblk::Grackle::Preview::AddJobsToWaitGroupResponse
          rpc :CompleteJobsFromWaitGroup, ::Evrblk::Grackle::Preview::CompleteJobsFromWaitGroupRequest, ::Evrblk::Grackle::Preview::CompleteJobsFromWaitGroupResponse
          rpc :AcquireLock, ::Evrblk::Grackle::Preview::AcquireLockRequest, ::Evrblk::Grackle::Preview::AcquireLockResponse
          rpc :ReleaseLock, ::Evrblk::Grackle::Preview::ReleaseLockRequest, ::Evrblk::Grackle::Preview::ReleaseLockResponse
          rpc :GetLock, ::Evrblk::Grackle::Preview::GetLockRequest, ::Evrblk::Grackle::Preview::GetLockResponse
          rpc :DeleteLock, ::Evrblk::Grackle::Preview::DeleteLockRequest, ::Evrblk::Grackle::Preview::DeleteLockResponse
          rpc :ListLocks, ::Evrblk::Grackle::Preview::ListLocksRequest, ::Evrblk::Grackle::Preview::ListLocksResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
