# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: grackle/v1beta/api.proto for package 'Evrblk.Grackle.V1Beta'

require 'grpc'
require 'evrblk/grackle/v1beta/api_pb'

module Evrblk
  module Grackle
    module V1Beta
      module GrackleApi
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'com.evrblk.grackle.v1beta.GrackleApi'

          rpc :CreateNamespace, ::Evrblk::Grackle::V1Beta::CreateNamespaceRequest, ::Evrblk::Grackle::V1Beta::CreateNamespaceResponse
          rpc :ListNamespaces, ::Evrblk::Grackle::V1Beta::ListNamespacesRequest, ::Evrblk::Grackle::V1Beta::ListNamespacesResponse
          rpc :GetNamespace, ::Evrblk::Grackle::V1Beta::GetNamespaceRequest, ::Evrblk::Grackle::V1Beta::GetNamespaceResponse
          rpc :DeleteNamespace, ::Evrblk::Grackle::V1Beta::DeleteNamespaceRequest, ::Evrblk::Grackle::V1Beta::DeleteNamespaceResponse
          rpc :UpdateNamespace, ::Evrblk::Grackle::V1Beta::UpdateNamespaceRequest, ::Evrblk::Grackle::V1Beta::UpdateNamespaceResponse
          rpc :CreateSemaphore, ::Evrblk::Grackle::V1Beta::CreateSemaphoreRequest, ::Evrblk::Grackle::V1Beta::CreateSemaphoreResponse
          rpc :ListSemaphores, ::Evrblk::Grackle::V1Beta::ListSemaphoresRequest, ::Evrblk::Grackle::V1Beta::ListSemaphoresResponse
          rpc :GetSemaphore, ::Evrblk::Grackle::V1Beta::GetSemaphoreRequest, ::Evrblk::Grackle::V1Beta::GetSemaphoreResponse
          rpc :AcquireSemaphore, ::Evrblk::Grackle::V1Beta::AcquireSemaphoreRequest, ::Evrblk::Grackle::V1Beta::AcquireSemaphoreResponse
          rpc :ReleaseSemaphore, ::Evrblk::Grackle::V1Beta::ReleaseSemaphoreRequest, ::Evrblk::Grackle::V1Beta::ReleaseSemaphoreResponse
          rpc :UpdateSemaphore, ::Evrblk::Grackle::V1Beta::UpdateSemaphoreRequest, ::Evrblk::Grackle::V1Beta::UpdateSemaphoreResponse
          rpc :DeleteSemaphore, ::Evrblk::Grackle::V1Beta::DeleteSemaphoreRequest, ::Evrblk::Grackle::V1Beta::DeleteSemaphoreResponse
          rpc :ListSemaphoreHolders, ::Evrblk::Grackle::V1Beta::ListSemaphoreHoldersRequest, ::Evrblk::Grackle::V1Beta::ListSemaphoreHoldersResponse
          rpc :CreateSemaphoreLease, ::Evrblk::Grackle::V1Beta::CreateSemaphoreLeaseRequest, ::Evrblk::Grackle::V1Beta::CreateSemaphoreLeaseResponse
          rpc :RevokeSemaphoreLease, ::Evrblk::Grackle::V1Beta::RevokeSemaphoreLeaseRequest, ::Evrblk::Grackle::V1Beta::RevokeSemaphoreLeaseResponse
          rpc :RefreshSemaphoreLease, ::Evrblk::Grackle::V1Beta::RefreshSemaphoreLeaseRequest, ::Evrblk::Grackle::V1Beta::RefreshSemaphoreLeaseResponse
          rpc :ListSemaphoreLeases, ::Evrblk::Grackle::V1Beta::ListSemaphoreLeasesRequest, ::Evrblk::Grackle::V1Beta::ListSemaphoreLeasesResponse
          rpc :GetSemaphoreLease, ::Evrblk::Grackle::V1Beta::GetSemaphoreLeaseRequest, ::Evrblk::Grackle::V1Beta::GetSemaphoreLeaseResponse
          rpc :CreateWaitGroup, ::Evrblk::Grackle::V1Beta::CreateWaitGroupRequest, ::Evrblk::Grackle::V1Beta::CreateWaitGroupResponse
          rpc :UpdateWaitGroup, ::Evrblk::Grackle::V1Beta::UpdateWaitGroupRequest, ::Evrblk::Grackle::V1Beta::UpdateWaitGroupResponse
          rpc :ListWaitGroups, ::Evrblk::Grackle::V1Beta::ListWaitGroupsRequest, ::Evrblk::Grackle::V1Beta::ListWaitGroupsResponse
          rpc :GetWaitGroup, ::Evrblk::Grackle::V1Beta::GetWaitGroupRequest, ::Evrblk::Grackle::V1Beta::GetWaitGroupResponse
          rpc :DeleteWaitGroup, ::Evrblk::Grackle::V1Beta::DeleteWaitGroupRequest, ::Evrblk::Grackle::V1Beta::DeleteWaitGroupResponse
          rpc :CompleteJobsFromWaitGroup, ::Evrblk::Grackle::V1Beta::CompleteJobsFromWaitGroupRequest, ::Evrblk::Grackle::V1Beta::CompleteJobsFromWaitGroupResponse
          rpc :ListWaitGroupCompletedJobs, ::Evrblk::Grackle::V1Beta::ListWaitGroupCompletedJobsRequest, ::Evrblk::Grackle::V1Beta::ListWaitGroupCompletedJobsResponse
          rpc :WaitForWaitGroup, ::Evrblk::Grackle::V1Beta::WaitForWaitGroupRequest, ::Evrblk::Grackle::V1Beta::WaitForWaitGroupResponse
          rpc :AcquireLock, ::Evrblk::Grackle::V1Beta::AcquireLockRequest, ::Evrblk::Grackle::V1Beta::AcquireLockResponse
          rpc :ReleaseLock, ::Evrblk::Grackle::V1Beta::ReleaseLockRequest, ::Evrblk::Grackle::V1Beta::ReleaseLockResponse
          rpc :GetLock, ::Evrblk::Grackle::V1Beta::GetLockRequest, ::Evrblk::Grackle::V1Beta::GetLockResponse
          rpc :DeleteLock, ::Evrblk::Grackle::V1Beta::DeleteLockRequest, ::Evrblk::Grackle::V1Beta::DeleteLockResponse
          rpc :ListLocks, ::Evrblk::Grackle::V1Beta::ListLocksRequest, ::Evrblk::Grackle::V1Beta::ListLocksResponse
          rpc :CreateLockLease, ::Evrblk::Grackle::V1Beta::CreateLockLeaseRequest, ::Evrblk::Grackle::V1Beta::CreateLockLeaseResponse
          rpc :RevokeLockLease, ::Evrblk::Grackle::V1Beta::RevokeLockLeaseRequest, ::Evrblk::Grackle::V1Beta::RevokeLockLeaseResponse
          rpc :RefreshLockLease, ::Evrblk::Grackle::V1Beta::RefreshLockLeaseRequest, ::Evrblk::Grackle::V1Beta::RefreshLockLeaseResponse
          rpc :ListLockLeases, ::Evrblk::Grackle::V1Beta::ListLockLeasesRequest, ::Evrblk::Grackle::V1Beta::ListLockLeasesResponse
          rpc :GetLockLease, ::Evrblk::Grackle::V1Beta::GetLockLeaseRequest, ::Evrblk::Grackle::V1Beta::GetLockLeaseResponse
          rpc :CreateBarrier, ::Evrblk::Grackle::V1Beta::CreateBarrierRequest, ::Evrblk::Grackle::V1Beta::CreateBarrierResponse
          rpc :ListBarriers, ::Evrblk::Grackle::V1Beta::ListBarriersRequest, ::Evrblk::Grackle::V1Beta::ListBarriersResponse
          rpc :GetBarrier, ::Evrblk::Grackle::V1Beta::GetBarrierRequest, ::Evrblk::Grackle::V1Beta::GetBarrierResponse
          rpc :DeleteBarrier, ::Evrblk::Grackle::V1Beta::DeleteBarrierRequest, ::Evrblk::Grackle::V1Beta::DeleteBarrierResponse
          rpc :UpdateBarrier, ::Evrblk::Grackle::V1Beta::UpdateBarrierRequest, ::Evrblk::Grackle::V1Beta::UpdateBarrierResponse
          rpc :ArriveAtBarrier, ::Evrblk::Grackle::V1Beta::ArriveAtBarrierRequest, ::Evrblk::Grackle::V1Beta::ArriveAtBarrierResponse
          rpc :WaitAtBarrier, ::Evrblk::Grackle::V1Beta::WaitAtBarrierRequest, ::Evrblk::Grackle::V1Beta::WaitAtBarrierResponse
          rpc :ListBarrierParticipants, ::Evrblk::Grackle::V1Beta::ListBarrierParticipantsRequest, ::Evrblk::Grackle::V1Beta::ListBarrierParticipantsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
