# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: myaccount/preview/api.proto for package 'Evrblk.MyAccount.Preview'

require 'grpc'
require 'evrblk/myaccount/preview/api_pb'

module Evrblk
  module MyAccount
    module Preview
      module MyAccountPreviewApi
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'com.evrblk.myaccount.preview.MyAccountPreviewApi'

          rpc :GetAccount, ::Evrblk::MyAccount::Preview::GetAccountRequest, ::Evrblk::MyAccount::Preview::GetAccountResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
