# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: iam/preview/api.proto for package 'Evrblk.IAM.Preview'

require 'grpc'
require 'evrblk/iam/preview/api_pb'

module Evrblk
  module IAM
    module Preview
      module IamPreviewApi
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'com.evrblk.iam.preview.IamPreviewApi'

          rpc :CreateRole, ::Evrblk::IAM::Preview::CreateRoleRequest, ::Evrblk::IAM::Preview::CreateRoleResponse
          rpc :GetRole, ::Evrblk::IAM::Preview::GetRoleRequest, ::Evrblk::IAM::Preview::GetRoleResponse
          rpc :UpdateRole, ::Evrblk::IAM::Preview::UpdateRoleRequest, ::Evrblk::IAM::Preview::UpdateRoleResponse
          rpc :ListRoles, ::Evrblk::IAM::Preview::ListRolesRequest, ::Evrblk::IAM::Preview::ListRolesResponse
          rpc :DeleteRole, ::Evrblk::IAM::Preview::DeleteRoleRequest, ::Evrblk::IAM::Preview::DeleteRoleResponse
          rpc :CreateUser, ::Evrblk::IAM::Preview::CreateUserRequest, ::Evrblk::IAM::Preview::CreateUserResponse
          rpc :GetUser, ::Evrblk::IAM::Preview::GetUserRequest, ::Evrblk::IAM::Preview::GetUserResponse
          rpc :UpdateUser, ::Evrblk::IAM::Preview::UpdateUserRequest, ::Evrblk::IAM::Preview::UpdateUserResponse
          rpc :ListUsers, ::Evrblk::IAM::Preview::ListUsersRequest, ::Evrblk::IAM::Preview::ListUsersResponse
          rpc :DeleteUser, ::Evrblk::IAM::Preview::DeleteUserRequest, ::Evrblk::IAM::Preview::DeleteUserResponse
          rpc :CreateApiKey, ::Evrblk::IAM::Preview::CreateApiKeyRequest, ::Evrblk::IAM::Preview::CreateApiKeyResponse
          rpc :GetApiKey, ::Evrblk::IAM::Preview::GetApiKeyRequest, ::Evrblk::IAM::Preview::GetApiKeyResponse
          rpc :ListApiKeys, ::Evrblk::IAM::Preview::ListApiKeysRequest, ::Evrblk::IAM::Preview::ListApiKeysResponse
          rpc :DeleteApiKey, ::Evrblk::IAM::Preview::DeleteApiKeyRequest, ::Evrblk::IAM::Preview::DeleteApiKeyResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
